# Generated by Django 5.0.2 on 2024-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_adopcion',
            name='respuesta',
            field=models.TextField(default=''),
        ),
    ]
